@startuml

skinparam activity {
    FontColor          white
    FontSize           14
    AttributeFontname  Arial Narrow
    BackgroundColor    #527BC6
    BorderColor        black
    ArrowColor         #222266
}

center header
Model 1
endheader

|Level 1|
start
:Step 1;
|#AntiqueWhite|Level 2|
:Step 2;
|Level 3|
:Step 3;
partition Step-3 {
if (Here == Not Here) then
-> YES;
:Go;
else
-> NO;
:Dont Go;
endif
}
|Level 1|
while (Step 4)
	:read data;
	:generate diagrams;
	endwhile
:Step 5;
|Level 2|
:Step 6;
split
:Step 7;
split again
:Step 8;
end split
|#PowderBlue|Level 4|
:Step 9;
:Step 10;
|Level 2|
stop

@enduml
